name: Experiment/Production Job

on:
  push:
    paths:
      - src/model/**
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Trigger Dev Azure Machine Learning job
      run: >-
        az ml job create
        --file src/job-dev.yml
        --resource-group ${{ vars.RESOURCE_GROUP }}
        --workspace-name ${{ vars.WORKSPACE_NAME }}
        --stream
  production:
    needs: ['experiment']
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Trigger Prod Azure Machine Learning job
      run: >-
        az ml job create
        --file src/job-prod.yml
        --resource-group ${{ vars.RESOURCE_GROUP }}
        --workspace-name ${{ vars.WORKSPACE_NAME }}







